apiVersion: v1
data:
  scrape.yml: |2

    global:
      scrape_interval: 10s

    scrape_configs:
    - honor_labels: true
      job_name: federate
      metrics_path: /federate
      params:
        match[]:
        - '{rmrw="allowed"}'
        - '{__name__=~"up|node_cpu_seconds_total|node_memory_MemTotal_bytes|node_memory_MemAvailable_bytes|node_filesystem_free_bytes"}'
        - '{__name__=~"container_cpu_usage_seconds_total|container_memory_usage_bytes|container_memory_working_set_bytes|container_network_receive_bytes_total|container_network_transmit_bytes_total|container_cpu_cfs_throttled_seconds_total"}'
      scrape_interval: 15s
      static_configs:
      - targets:
        - kps-kube-prometheus-stack-prometheus.monitoring:9090
kind: ConfigMap
metadata:
  name: vma-agent-config
  namespace: monitoring
