vmselect:
  enabled: true
  name: vmselect
  image:
    repository: victoriametrics/vmselect
    tag: v1.96.0-cluster
    pullPolicy: IfNotPresent
  replicaCount: 1
vminsert:
  enabled: true
  name: vminsert
  image:
    repository: victoriametrics/vminsert
    tag: v1.96.0-cluster
    pullPolicy: IfNotPresent
  replicaCount: 1
vmstorage:
  enabled: true
  name: vmstorage
  image:
    repository: victoriametrics/vmstorage
    tag: v1.96.0-cluster
    pullPolicy: IfNotPresent
  retentionPeriod: 1
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json

  extraVolumes:
    []
    # - name: example
    #   configMap:
    #     name: example

  # Extra Volume Mounts for the container
  extraVolumeMounts:
    []
    # - name: example
    #   mountPath: /example
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    storageClass: ""
    mountPath: /storage
    size: 8Gi
    subPath: ""
  replicaCount: 1
